server:
  port: 8090

spring:
  application:
    name: phone
  jpa:
    defer-datasource-initialization: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  aop:
    proxy-target-class: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/spring-app

custom:
  service:
    url: https://api.example.com
    timeout: 5000

jwt:
  jwks-url: http://localhost:9090/realms/spring-app/protocol/openid-connect/certs