INSERT INTO PHONE (NAME) VALUES ('iPhone');
INSERT INTO PHONE (NAME) VALUES ('Samsung Galaxy');
INSERT INTO PHONE (NAME) VALUES ('Google Pixel');
INSERT INTO PHONE (NAME) VALUES ('Google Pixel');
INSERT INTO PHONE (NAME) VALUES ('OnePlus');
INSERT INTO PHONE (NAME) VALUES ('Nokia');
INSERT INTO PHONE (NAME) VALUES ('Sony Xperia');
INSERT INTO PHONE (NAME) VALUES ('Sony Xperia');